### PR TITLE
Corrected the interchanger documentation.

### PR DESCRIPTION
**Pull request by Jack12816**
**- What is it good for**

Related to the last `1.4.0` release, the documented custom Base64 interchanger does not work anymore. The default interchanger maps the original batch parameters into an array [with symbolized key hashes](https://github.com/karafka/sidekiq-backend/blob/e5fa3d2884f940d3bc032a3c30ad13424109cd91/lib/karafka/interchanger.rb#L18-L19). Unfortunately, [the next step at the parameter builder](https://github.com/karafka/sidekiq-backend/blob/e5fa3d2884f940d3bc032a3c30ad13424109cd91/lib/karafka/extensions/params_builder.rb#L14-L15) tries to read and merge string keys. The parameters hash is a plain object which will raise `KeyError: key not found: "metadata"` exceptions due to the different key types. 

**- What I did**

* Updated the readme documentation of the custom Base64 interchanger
* Converted the symbolized hash keys to strings at the default interchanger#encode method
* Corrected the specs for the default interchanger details

**- A picture of a cute animal (not mandatory but encouraged)**

images

### CODE REVIEW

**Review by mensfeld — APPROVED** [review]

**Comment by mensfeld** [comment]
@nijikon could you check why specs did not run? ^^

**Comment by mensfeld** [comment]
@Jack12816 thank you so much <3 this interchanger is not something that I use, thus completely forgot :(

**Comment by mensfeld** [comment]
@Jack12816 I'm going to craft a release as well in a sec.

**Comment by Jack12816** [comment]
@mensfeld Thanks merging! :) Would you mind to add the `hacktoberfest-accepted` label at this PR? :)

**Comment by mensfeld** [comment]
> Would you mind to add the hacktoberfest-accepted label at this PR? :)

No problem at all.

**Pull request merged**
